// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrorCode.proto

package com.indigo.sample.mmorpg.protocol;

public final class ErrorCode {
  private ErrorCode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *错误码
   * </pre>
   *
   * Protobuf enum {@code ID}
   */
  public enum ID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *鉴权失败
     * </pre>
     *
     * <code>AUTH_FAILED = 1;</code>
     */
    AUTH_FAILED(1),
    /**
     * <pre>
     *服务器未启动完毕
     * </pre>
     *
     * <code>SERVER_NOT_READY = 2;</code>
     */
    SERVER_NOT_READY(2),
    /**
     * <pre>
     *角色不存在
     * </pre>
     *
     * <code>CHARACTER_NOT_EXIST = 3;</code>
     */
    CHARACTER_NOT_EXIST(3),
    ;

    /**
     * <pre>
     *鉴权失败
     * </pre>
     *
     * <code>AUTH_FAILED = 1;</code>
     */
    public static final int AUTH_FAILED_VALUE = 1;
    /**
     * <pre>
     *服务器未启动完毕
     * </pre>
     *
     * <code>SERVER_NOT_READY = 2;</code>
     */
    public static final int SERVER_NOT_READY_VALUE = 2;
    /**
     * <pre>
     *角色不存在
     * </pre>
     *
     * <code>CHARACTER_NOT_EXIST = 3;</code>
     */
    public static final int CHARACTER_NOT_EXIST_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ID valueOf(int value) {
      return forNumber(value);
    }

    public static ID forNumber(int value) {
      switch (value) {
        case 1: return AUTH_FAILED;
        case 2: return SERVER_NOT_READY;
        case 3: return CHARACTER_NOT_EXIST;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ID> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ID>() {
            public ID findValueByNumber(int number) {
              return ID.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.indigo.sample.mmorpg.protocol.ErrorCode.getDescriptor().getEnumTypes().get(0);
    }

    private static final ID[] VALUES = values();

    public static ID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ID(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ID)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ErrorCode.proto*D\n\002ID\022\017\n\013AUTH_FAILED\020\001" +
      "\022\024\n\020SERVER_NOT_READY\020\002\022\027\n\023CHARACTER_NOT_" +
      "EXIST\020\003B#\n!com.indigo.sample.mmorpg.prot" +
      "ocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
