// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerProto.proto

package com.indigo.sample.mmorpg.protocol;

public final class PlayerProto {
  private PlayerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerInfo_1612001OrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerInfo_1612001)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 level = 3;</code>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 3;</code>
     */
    int getLevel();

    /**
     * <code>required int32 gender = 4;</code>
     */
    boolean hasGender();
    /**
     * <code>required int32 gender = 4;</code>
     */
    int getGender();

    /**
     * <code>required int32 clazz = 5;</code>
     */
    boolean hasClazz();
    /**
     * <code>required int32 clazz = 5;</code>
     */
    int getClazz();
  }
  /**
   * <pre>
   *角色的基本信息
   * </pre>
   *
   * Protobuf type {@code PlayerInfo_1612001}
   */
  public  static final class PlayerInfo_1612001 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerInfo_1612001)
      PlayerInfo_1612001OrBuilder {
    // Use PlayerInfo_1612001.newBuilder() to construct.
    private PlayerInfo_1612001(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerInfo_1612001() {
      id_ = 0L;
      name_ = "";
      level_ = 0;
      gender_ = 0;
      clazz_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerInfo_1612001(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              level_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              gender_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              clazz_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.indigo.sample.mmorpg.protocol.PlayerProto.internal_static_PlayerInfo_1612001_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.indigo.sample.mmorpg.protocol.PlayerProto.internal_static_PlayerInfo_1612001_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001.class, com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 3;
    private int level_;
    /**
     * <code>required int32 level = 3;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 level = 3;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int GENDER_FIELD_NUMBER = 4;
    private int gender_;
    /**
     * <code>required int32 gender = 4;</code>
     */
    public boolean hasGender() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 gender = 4;</code>
     */
    public int getGender() {
      return gender_;
    }

    public static final int CLAZZ_FIELD_NUMBER = 5;
    private int clazz_;
    /**
     * <code>required int32 clazz = 5;</code>
     */
    public boolean hasClazz() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 clazz = 5;</code>
     */
    public int getClazz() {
      return clazz_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClazz()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, gender_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, clazz_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, gender_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, clazz_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001)) {
        return super.equals(obj);
      }
      com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 other = (com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasLevel() == other.hasLevel());
      if (hasLevel()) {
        result = result && (getLevel()
            == other.getLevel());
      }
      result = result && (hasGender() == other.hasGender());
      if (hasGender()) {
        result = result && (getGender()
            == other.getGender());
      }
      result = result && (hasClazz() == other.hasClazz());
      if (hasClazz()) {
        result = result && (getClazz()
            == other.getClazz());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasLevel()) {
        hash = (37 * hash) + LEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getLevel();
      }
      if (hasGender()) {
        hash = (37 * hash) + GENDER_FIELD_NUMBER;
        hash = (53 * hash) + getGender();
      }
      if (hasClazz()) {
        hash = (37 * hash) + CLAZZ_FIELD_NUMBER;
        hash = (53 * hash) + getClazz();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *角色的基本信息
     * </pre>
     *
     * Protobuf type {@code PlayerInfo_1612001}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerInfo_1612001)
        com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.indigo.sample.mmorpg.protocol.PlayerProto.internal_static_PlayerInfo_1612001_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.indigo.sample.mmorpg.protocol.PlayerProto.internal_static_PlayerInfo_1612001_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001.class, com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001.Builder.class);
      }

      // Construct using com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        gender_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        clazz_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.indigo.sample.mmorpg.protocol.PlayerProto.internal_static_PlayerInfo_1612001_descriptor;
      }

      public com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 getDefaultInstanceForType() {
        return com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001.getDefaultInstance();
      }

      public com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 build() {
        com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 buildPartial() {
        com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 result = new com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gender_ = gender_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.clazz_ = clazz_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001) {
          return mergeFrom((com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 other) {
        if (other == com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasGender()) {
          setGender(other.getGender());
        }
        if (other.hasClazz()) {
          setClazz(other.getClazz());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        if (!hasLevel()) {
          return false;
        }
        if (!hasGender()) {
          return false;
        }
        if (!hasClazz()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>required int32 level = 3;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 level = 3;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 3;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000004;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 3;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0;
        onChanged();
        return this;
      }

      private int gender_ ;
      /**
       * <code>required int32 gender = 4;</code>
       */
      public boolean hasGender() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 gender = 4;</code>
       */
      public int getGender() {
        return gender_;
      }
      /**
       * <code>required int32 gender = 4;</code>
       */
      public Builder setGender(int value) {
        bitField0_ |= 0x00000008;
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 gender = 4;</code>
       */
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gender_ = 0;
        onChanged();
        return this;
      }

      private int clazz_ ;
      /**
       * <code>required int32 clazz = 5;</code>
       */
      public boolean hasClazz() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 clazz = 5;</code>
       */
      public int getClazz() {
        return clazz_;
      }
      /**
       * <code>required int32 clazz = 5;</code>
       */
      public Builder setClazz(int value) {
        bitField0_ |= 0x00000010;
        clazz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 clazz = 5;</code>
       */
      public Builder clearClazz() {
        bitField0_ = (bitField0_ & ~0x00000010);
        clazz_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PlayerInfo_1612001)
    }

    // @@protoc_insertion_point(class_scope:PlayerInfo_1612001)
    private static final com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001();
    }

    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PlayerInfo_1612001>
        PARSER = new com.google.protobuf.AbstractParser<PlayerInfo_1612001>() {
      public PlayerInfo_1612001 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlayerInfo_1612001(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerInfo_1612001> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerInfo_1612001> getParserForType() {
      return PARSER;
    }

    public com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerInfo_1612001 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerSpawn_1612002OrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerSpawn_1612002)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 mapId = 1;</code>
     */
    boolean hasMapId();
    /**
     * <code>required int32 mapId = 1;</code>
     */
    int getMapId();

    /**
     * <code>required int64 instanceId = 2;</code>
     */
    boolean hasInstanceId();
    /**
     * <code>required int64 instanceId = 2;</code>
     */
    long getInstanceId();

    /**
     * <code>required float x = 3;</code>
     */
    boolean hasX();
    /**
     * <code>required float x = 3;</code>
     */
    float getX();

    /**
     * <code>required float y = 4;</code>
     */
    boolean hasY();
    /**
     * <code>required float y = 4;</code>
     */
    float getY();
  }
  /**
   * <pre>
   *角色的位置信息
   * </pre>
   *
   * Protobuf type {@code PlayerSpawn_1612002}
   */
  public  static final class PlayerSpawn_1612002 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerSpawn_1612002)
      PlayerSpawn_1612002OrBuilder {
    // Use PlayerSpawn_1612002.newBuilder() to construct.
    private PlayerSpawn_1612002(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerSpawn_1612002() {
      mapId_ = 0;
      instanceId_ = 0L;
      x_ = 0F;
      y_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerSpawn_1612002(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              mapId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              instanceId_ = input.readInt64();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              x_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              y_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.indigo.sample.mmorpg.protocol.PlayerProto.internal_static_PlayerSpawn_1612002_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.indigo.sample.mmorpg.protocol.PlayerProto.internal_static_PlayerSpawn_1612002_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002.class, com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002.Builder.class);
    }

    private int bitField0_;
    public static final int MAPID_FIELD_NUMBER = 1;
    private int mapId_;
    /**
     * <code>required int32 mapId = 1;</code>
     */
    public boolean hasMapId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 mapId = 1;</code>
     */
    public int getMapId() {
      return mapId_;
    }

    public static final int INSTANCEID_FIELD_NUMBER = 2;
    private long instanceId_;
    /**
     * <code>required int64 instanceId = 2;</code>
     */
    public boolean hasInstanceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 instanceId = 2;</code>
     */
    public long getInstanceId() {
      return instanceId_;
    }

    public static final int X_FIELD_NUMBER = 3;
    private float x_;
    /**
     * <code>required float x = 3;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float x = 3;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 4;
    private float y_;
    /**
     * <code>required float y = 4;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float y = 4;</code>
     */
    public float getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMapId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInstanceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, mapId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, instanceId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, x_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, y_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, mapId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, instanceId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, x_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, y_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002)) {
        return super.equals(obj);
      }
      com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 other = (com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002) obj;

      boolean result = true;
      result = result && (hasMapId() == other.hasMapId());
      if (hasMapId()) {
        result = result && (getMapId()
            == other.getMapId());
      }
      result = result && (hasInstanceId() == other.hasInstanceId());
      if (hasInstanceId()) {
        result = result && (getInstanceId()
            == other.getInstanceId());
      }
      result = result && (hasX() == other.hasX());
      if (hasX()) {
        result = result && (
            java.lang.Float.floatToIntBits(getX())
            == java.lang.Float.floatToIntBits(
                other.getX()));
      }
      result = result && (hasY() == other.hasY());
      if (hasY()) {
        result = result && (
            java.lang.Float.floatToIntBits(getY())
            == java.lang.Float.floatToIntBits(
                other.getY()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMapId()) {
        hash = (37 * hash) + MAPID_FIELD_NUMBER;
        hash = (53 * hash) + getMapId();
      }
      if (hasInstanceId()) {
        hash = (37 * hash) + INSTANCEID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getInstanceId());
      }
      if (hasX()) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getX());
      }
      if (hasY()) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getY());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *角色的位置信息
     * </pre>
     *
     * Protobuf type {@code PlayerSpawn_1612002}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerSpawn_1612002)
        com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.indigo.sample.mmorpg.protocol.PlayerProto.internal_static_PlayerSpawn_1612002_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.indigo.sample.mmorpg.protocol.PlayerProto.internal_static_PlayerSpawn_1612002_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002.class, com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002.Builder.class);
      }

      // Construct using com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        mapId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        instanceId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.indigo.sample.mmorpg.protocol.PlayerProto.internal_static_PlayerSpawn_1612002_descriptor;
      }

      public com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 getDefaultInstanceForType() {
        return com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002.getDefaultInstance();
      }

      public com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 build() {
        com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 buildPartial() {
        com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 result = new com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mapId_ = mapId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.instanceId_ = instanceId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002) {
          return mergeFrom((com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 other) {
        if (other == com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002.getDefaultInstance()) return this;
        if (other.hasMapId()) {
          setMapId(other.getMapId());
        }
        if (other.hasInstanceId()) {
          setInstanceId(other.getInstanceId());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMapId()) {
          return false;
        }
        if (!hasInstanceId()) {
          return false;
        }
        if (!hasX()) {
          return false;
        }
        if (!hasY()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int mapId_ ;
      /**
       * <code>required int32 mapId = 1;</code>
       */
      public boolean hasMapId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 mapId = 1;</code>
       */
      public int getMapId() {
        return mapId_;
      }
      /**
       * <code>required int32 mapId = 1;</code>
       */
      public Builder setMapId(int value) {
        bitField0_ |= 0x00000001;
        mapId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 mapId = 1;</code>
       */
      public Builder clearMapId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mapId_ = 0;
        onChanged();
        return this;
      }

      private long instanceId_ ;
      /**
       * <code>required int64 instanceId = 2;</code>
       */
      public boolean hasInstanceId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 instanceId = 2;</code>
       */
      public long getInstanceId() {
        return instanceId_;
      }
      /**
       * <code>required int64 instanceId = 2;</code>
       */
      public Builder setInstanceId(long value) {
        bitField0_ |= 0x00000002;
        instanceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 instanceId = 2;</code>
       */
      public Builder clearInstanceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        instanceId_ = 0L;
        onChanged();
        return this;
      }

      private float x_ ;
      /**
       * <code>required float x = 3;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float x = 3;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>required float x = 3;</code>
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000004;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float x = 3;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000004);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>required float y = 4;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float y = 4;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>required float y = 4;</code>
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000008;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float y = 4;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000008);
        y_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PlayerSpawn_1612002)
    }

    // @@protoc_insertion_point(class_scope:PlayerSpawn_1612002)
    private static final com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002();
    }

    public static com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PlayerSpawn_1612002>
        PARSER = new com.google.protobuf.AbstractParser<PlayerSpawn_1612002>() {
      public PlayerSpawn_1612002 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlayerSpawn_1612002(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerSpawn_1612002> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerSpawn_1612002> getParserForType() {
      return PARSER;
    }

    public com.indigo.sample.mmorpg.protocol.PlayerProto.PlayerSpawn_1612002 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerInfo_1612001_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerInfo_1612001_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerSpawn_1612002_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerSpawn_1612002_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PlayerProto.proto\"\\\n\022PlayerInfo_161200" +
      "1\022\n\n\002id\030\001 \002(\003\022\014\n\004name\030\002 \002(\t\022\r\n\005level\030\003 \002" +
      "(\005\022\016\n\006gender\030\004 \002(\005\022\r\n\005clazz\030\005 \002(\005\"N\n\023Pla" +
      "yerSpawn_1612002\022\r\n\005mapId\030\001 \002(\005\022\022\n\ninsta" +
      "nceId\030\002 \002(\003\022\t\n\001x\030\003 \002(\002\022\t\n\001y\030\004 \002(\002B#\n!com" +
      ".indigo.sample.mmorpg.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PlayerInfo_1612001_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerInfo_1612001_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerInfo_1612001_descriptor,
        new java.lang.String[] { "Id", "Name", "Level", "Gender", "Clazz", });
    internal_static_PlayerSpawn_1612002_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PlayerSpawn_1612002_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerSpawn_1612002_descriptor,
        new java.lang.String[] { "MapId", "InstanceId", "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
